### ISSUE TITLE
⏩ Pull Request code checks

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/tech-docs-monitor#7]
**User Story**
As a Cloud Ops engineer
I expect code format is checked when a pull request is submitted
So that linting errors are flagged before getting merged.

**Value / Purpose**
Testing of code
Reduction of errors when Actions run

**Useful Contacts**
Rich

Definition of Done
GitHub Action is checking PR's

**Comment by mitchdawson1982** [comment]
Possible Linters - Gov UK
